Repository gobuffalo/buffalo, pull requests merged in 2023-01, with the labels that each got.

#2359 For nulls.Time, decode empty value as NULL
  binding/decoders/null_time.go
  binding/decoders/null_time_test.go
Labels: bug, s: accepted

#2361 enabled stack trace when the original error support it (in dev and event)
  error.dev.html
  errors.go
Labels: enhancement

#2363 process: version bump and module update
  SHOULDERS.md
  go.mod
  go.sum
  runtime/version.go
Labels: dependency, process
